[package]
name = "fyle-base"
version = "0.0.0"
authors = ["Dylan Roskilly <fyle@dylanroskilly.me>"]
edition = "2024"
license = "MIT"
description = "FTP primitives and utilities"
repository = "https://github.com/DylanRoskilly/fyle"
