[package]
name = "fyle"
version = "0.0.0"
authors = ["Dylan Roskilly <fyle@dylanroskilly.me>"]
edition = "2024"
license = "MIT"
description = "FTP server"
repository = "https://github.com/DylanRoskilly/fyle"
